### ISSUE TITLE
A general TODO list

### ISSUE THREAD

**Issue by IceDragon200** [polyfox/moon#18]
* [x] Move Moon::Text into the core (#11 Which is solved by #15)
* [ ] Remove GLFW dependency from `moon-system`, (#16)
* [ ] Get GLFW statically linked (#17)

**Comment by IceDragon200** [comment]
All tests will fail until #17 and #16 are merged
